version: 1

environment:
  php: 8.2
  node: 20

on:
  push:
    branches:
      - ci

# Add the following 2 pipeline steps to your Chipper CI pipeline:
pipeline:
  - name: Configure Forge
    cmd: |
      echo $SSH_PRIVATE_KEY > ~/.ssh/id_forge
      chmod 0600 ~/.ssh/id_forge
      composer global require laravel/forge-cli

  - name: Deploy
    cmd: |
      forge server:switch your-server-name
      forge deploy your-site-name.com
