version: 1

environment:
  php: 8.2
  node: 20

services:
  - redis:
  - mysql: 8

on:
  pull_request:
    branches: .*
  push:
    branches:
      - main

pipeline:
  # - name: Setup
  #   cmd: |
  #     cp -v .env .env.testing
  #     composer install --no-interaction --optimize-autoloader
  #     php artisan migrate --force

  # - name: Compile Dev Assets
  #   cmd: |
  #     npm ci --no-audit
  #     npm run build

  # # - name: ESLint
  # #   cmd: npm run lint

  # - name: Run Tests
  #   cmd: ./vendor/bin/pest


  - name: Configure Forge
    cmd: |
      echo $SSH_PRIVATE_KEY > ~/.ssh/id_forge
      chmod 0600 ~/.ssh/id_forge
      composer global require laravel/forge-cli

  - name: Deploy
    cmd: |
      forge server:switch services-env-01
      forge deploy jfk-ci.services.scala.com