version: 1

environment:
  php: 8.2
  node: 20

services:
  - redis:
  - mysql: 8

on:
  pull_request:
    branches: .*
  push:
    branches:
      - main

pipeline:
  # - name: Setup
  #   cmd: |
  #     cp -v .env
  #     composer install -q --no-interaction --prefer-dist --optimize-autoloader
  #     php artisan key:generate
  #     php artisan migrate:seed

  # - name: Compile Dev Assets
  #   cmd: |
  #     npm ci --no-audit
  #     npm run build

  # - name: ESLint
  #   cmd: npm run lint

  - name: Run Tests
    cmd: ./vendor/bin/pest

  - name: Configure Forge
    cmd: |
      echo $SSH_PRIVATE_KEY > ~/.ssh/id_forge
      chmod 0600 ~/.ssh/id_forge
      composer global require laravel/forge-cli

  - name: Deploy
    cmd: |
      forge deploy jfk-ci.services.scala.com